In [163]:
import pandas as pd
url = "https://fr.wikipedia.org/wiki/Coupe_du_monde_de_football_2022"
wc2022 = pd.read_html(url)
wc2022

[                   0                                        1
 0              Sport                                 Football
 1    Organisateur(s)                                     FIFA
 2           Éditions                                      22e
 3            Lieu(x)                                    Qatar
 4               Date       du 20 novembre au 18 décembre 2022
 5       Participants  32 équipes 210 en phases qualificatives
 6           Épreuves                            64 rencontres
 7            Site(s)                                 8 stades
 8  Site web officiel                            Site officiel,
                        0                       1
 0        Tenant du titre              France (2)
 1              Vainqueur           Argentine (3)
 2              Finaliste                  France
 3              Troisième                 Croatie
 4                   Buts    172 (2,69 par match)
 5        Meilleur joueur            Lionel Messi
 6  Meilleur(s) buteur(s)  Kylian Mbappé (8 buts),
   Fédérations candidates  1er tour 2e tour 3e tour 4e tour
 0                  Qatar        11      10      11      14
 1             États-Unis         3       5       6       8
 2           Corée du Sud         4       5       5       -
 3                  Japon         3       2       -       -
 4              Australie         1       -       -       -
 5        Total des votes        22      22      22      22,
                                                     0  \
 0                                              Lusail
 1                 Stade de Lusail[36] (nouveau stade)
 2                     Capacité : 88 966[39],[40],[41]
 3                                                 NaN
 4                       Présentation du stade en 360°
 5                                             Al-Khor
 6                   Stade Al-Bayt[51] (nouveau stade)
 7                     Capacité : 68 895[55],[56],[57]
 8                                                 NaN
 9                       Présentation du stade en 360°
 10  Villes hôtes Lusail Doha Al-Khor Al-Wakrah Al-...

                                                     1  \
 0                                                Doha
 1                          Stade 974 (stade éphémère)
 2            Capacité : 44 089[42],[43],[44],[note 1]
 3                                                 NaN
 4                       Présentation du stade en 360°
 5                                           Al-Rayyan
 6              Stade Ahmad-ben-Ali[52] (stade rénové)
 7            Capacité : 45 032[58],[59],[60],[note 2]
 8                                                 NaN
 9                       Présentation du stade en 360°
 10  Villes hôtes Lusail Doha Al-Khor Al-Wakrah Al-...

                                                     2  \
 0                                                Doha
 1   Stade international de Khalifa[37] (stade rénové)
 2                     Capacité : 45 857[45],[46],[47]
 3                                                 NaN
 4                       Présentation du stade en 360°
 5                                           Al-Rayyan
 6            Stade Education City[53] (nouveau stade)
 7                     Capacité : 44 667[61],[62],[63]
 8                                                 NaN
 9                       Présentation du stade en 360°
 10  Aire urbaine de Doha Education City Stade 974 ...

                                                     3
 0                                                Doha
 1                Stade Al-Thumama[38] (nouveau stade)
 2                     Capacité : 44 400[48],[49],[50]
 3                                                 NaN
 4                       Présentation du stade en 360°
 5                                           Al-Wakrah
 6                 Stade Al-Janoub[54] (nouveau stade)
 7            Capacité : 44 325[64],[65],[66],[note 3]
 8                                                 NaN
 9                       Présentation du stade en 360°
 10  Aire urbaine de Doha Education City Stade 974 ...  ,
                                                    0  \
 0                                              Carte
 1  Équipes qualifiées pour la Coupe du monde 2022...
 2                          Océanie (OFC) 0 places[c]
 3                                                NaN

                                                    1  \
 0                            Europe (UEFA) 13 places
 1  Allemagne : 20e phase finale  Angleterre : 16e...
 2  Allemagne : 20e phase finale  Angleterre : 16e...
 3  Allemagne : 20e phase finale  Angleterre : 16e...

                                                    2  \
 0             Amérique du Sud (CONMEBOL) 4 places[a]
 1  Brésil : 22e phase finale  Argentine : 18e pha...
 2  Amérique du Nord, Centrale et Caraïbes (CONCAC...
 3  Mexique : 17e phase finale  États-Unis : 11e p...

                                                    3
 0                             Afrique (CAF) 5 places
 1  Cameroun : 8e phase finale  Maroc : 6e phase f...
 2     Asie (AFC) 6 places[e] (dont une au pays hôte)
 3  Corée du Sud : 11e phase finale  Japon : 7e ph...  ,
   Confédération                                           Arbitres  \
 0           AFC  Abdulrahman Al-Jassim  Chris Beath  Alireza Fa...
 1           CAF  Bakary Gassama  Mustapha Ghorbal  Victor Gomes...
 2           OFC                                     Matthew Conger
 3      CONCACAF  Iván Barton  Ismail Elfath  Mario Escobar  Sai...
 4      CONMEBOL  Raphael Claus  Andrés Matonte  Kevin Ortega  F...
 5          UEFA  Stéphanie Frappart  István Kovács  Danny Makke...

                                  Arbitres assistants  \
 0  Mohammadreza Abolfazli  Taleb Al-Marri  Mohame...
 1  Mahmoud Abouelregal  Djibril Camara  Gerson Do...
 2                         Tevita Makasini  Mark Rule
 3  Kyle Atkins  Karen Diaz Medina  Raymundo Helpy...
 4  Neuza Back  Juan Pablo Belatti  Diego Bonfá  B...
 5  Mihai Artene  Simon Bennett  Gary Beswick  Stu...

                                       Arbitres vidéo
 0  Abdulla Al-Marri  Muhammad Bin Jahari  Shaun E...
 1                        Rédouane Jiyed  Adil Zourak
 2                                      Aucun arbitre
 3  Drew Fischer  Fernando Guerrero  Armando Villa...
 4  Julio Bascuñán  Nicolás Gallo  Leodán González...
 5  Jérôme Brisard  Bastian Dankert  Ricardo de Bu...  ,
    Joueurs                                         Clubs
 0       16  Bayern Munich, Manchester City, FC Barcelone
 1       15                                    Al-Sadd SC
 2       14                             Manchester United,
                                            Chapeau 1  \
 0  Qatar (pays hôte) (51) Brésil (1) Belgique (2)...

                                            Chapeau 2  \
 0  Mexique (9) Pays-Bas (10) Danemark (11) Allema...

                                            Chapeau 3  \
 0  Sénégal (20) Iran (21) Japon (23) Maroc (24) S...

                                            Chapeau 4
 0  Cameroun (37) Canada (38) Équateur (46) Arabie...  ,
           Groupe A             Groupe B              Groupe C  \
 0       Qatar (50)       Angleterre (5)         Argentine (3)
 1    Équateur (44)            Iran (20)  Arabie saoudite (51)
 2     Sénégal (18)      États-Unis (16)          Mexique (13)
 3     Pays-Bas (8)  Pays de Galles (19)          Pologne (26)
 4         Groupe E             Groupe F              Groupe G
 5      Espagne (7)         Belgique (2)            Brésil (1)
 6  Costa Rica (31)          Canada (41)           Serbie (21)
 7   Allemagne (11)           Maroc (22)           Suisse (15)
 8       Japon (24)         Croatie (12)         Cameroun (43)

             Groupe D
 0         France (4)
 1     Australie (38)
 2      Danemark (10)
 3       Tunisie (30)
 4           Groupe H
 5       Portugal (9)
 6         Ghana (61)
 7       Uruguay (14)
 8  Corée du Sud (28)  ,
      0         1    2  3  4  5  6   7   8     9
 0  NaN    Équipe  Pts  J  G  N  P  BP  BC  Diff
 1  1.0  Pays-Bas    7  3  2  1  0   5   1    +4
 2  2.0   Sénégal    6  3  2  0  1   5   4    +1
 3  3.0  Équateur    4  3  1  1  1   4   3    +1
 4  4.0     Qatar    0  3  0  0  3   1   7    -6,
                                     0      1        2  \
 0         Match 1 (match d'ouverture)  Qatar    0 - 2
 1  20 novembre 2022 19 h heure locale    NaN  (0 - 2)
 2  20 novembre 2022 19 h heure locale    NaN  Rapport

                                               3  \
 0                                      Équateur
 1  16e (pén.) Valencia 31e Valencia (Preciado )
 2                                           NaN

                                                    4  \
 0                             Stade Al-Bayt, Al-Khor
 1  Spectateurs : 67 372 Arbitrage : Daniele Orsat...
 2  Spectateurs : 67 372 Arbitrage : Daniele Orsat...

                                                    5
 0                                                NaN
 1  Spectateurs : 67 372 Arbitrage : Daniele Orsat...
 2  Spectateurs : 67 372 Arbitrage : Daniele Orsat...  ,
                                     0        1        2  \
 0                             Match 2  Sénégal    0 - 2
 1  21 novembre 2022 19 h heure locale      NaN  (0 - 0)
 2  21 novembre 2022 19 h heure locale      NaN  Rapport

                                       3  \
 0                              Pays-Bas
 1  84e Gakpo (de Jong )  90+9e Klaassen
 2                                   NaN

                                                    4  \
 0                             Stade Al-Thumama, Doha
 1  Spectateurs : 41 721 Arbitrage : Wilton Sampai...
 2  Spectateurs : 41 721 Arbitrage : Wilton Sampai...

                                                    5
 0                                                NaN
 1  Spectateurs : 41 721 Arbitrage : Wilton Sampai...
 2  Spectateurs : 41 721 Arbitrage : Wilton Sampai...  ,
                                     0                        1        2  \
 0                            Match 18                    Qatar    1 - 3
 1  25 novembre 2022 16 h heure locale  ( Mohammad) Muntari 78e  (0 - 1)
 2  25 novembre 2022 16 h heure locale                      NaN  Rapport

                                                    3  \
 0                                            Sénégal
 1  41e Dia 48e Diédhiou (Jakobs ) 84e Dieng (Ndia...
 2                                                NaN

                                                    4  \
 0                             Stade Al-Thumama, Doha
 1  Spectateurs : 41 797 Arbitrage : Antonio Mateu...
 2  Spectateurs : 41 797 Arbitrage : Antonio Mateu...

                                                    5
 0                                                NaN
 1  Spectateurs : 41 797 Arbitrage : Antonio Mateu...
 2  Spectateurs : 41 797 Arbitrage : Antonio Mateu...  ,
                                     0                     1        2  \
 0                            Match 19              Pays-Bas    1 - 1
 1  25 novembre 2022 19 h heure locale  ( Klaassen) Gakpo 6e  (1 - 0)
 2  25 novembre 2022 19 h heure locale                   NaN  Rapport

               3                                                  4  \
 0      Équateur               Stade international de Khalifa, Doha
 1  49e Valencia  Spectateurs : 44 833 Arbitrage : Mustapha Ghor...
 2           NaN  Spectateurs : 44 833 Arbitrage : Mustapha Ghor...

                                                    5
 0                                                NaN
 1  Spectateurs : 44 833 Arbitrage : Mustapha Ghor...
 2  Spectateurs : 44 833 Arbitrage : Mustapha Ghor...  ,
                                     0                                  1  \
 0                            Match 36                           Pays-Bas
 1  29 novembre 2022 18 h heure locale  ( Klaassen) Gakpo 26e de Jong 49e
 2  29 novembre 2022 18 h heure locale                                NaN

          2      3                                                  4  \
 0    2 - 0  Qatar                             Stade Al-Bayt, Al-Khor
 1  (1 - 0)    NaN  Spectateurs : 66 784 Arbitrage : Bakary Gassam...
 2  Rapport    NaN  Spectateurs : 66 784 Arbitrage : Bakary Gassam...

                                                    5
 0                                                NaN
 1  Spectateurs : 66 784 Arbitrage : Bakary Gassam...
 2  Spectateurs : 66 784 Arbitrage : Bakary Gassam...  ,
                                     0                      1        2  \
 0                            Match 35               Équateur    1 - 2
 1  29 novembre 2022 18 h heure locale  ( Torres) Caicedo 67e  (0 - 1)
 2  29 novembre 2022 18 h heure locale                    NaN  Rapport

                                 3  \
 0                         Sénégal
 1  44e (pén.) Sarr  70e Koulibaly
 2                             NaN

                                                    4  \
 0               Stade international de Khalifa, Doha
 1  Spectateurs : 44 569 Arbitrage : Clément Turpi...
 2  Spectateurs : 44 569 Arbitrage : Clément Turpi...

                                                    5
 0                                                NaN
 1  Spectateurs : 44 569 Arbitrage : Clément Turpi...
 2  Spectateurs : 44 569 Arbitrage : Clément Turpi...  ,
      0               1    2  3  4  5  6   7   8     9
 0  NaN          Équipe  Pts  J  G  N  P  BP  BC  Diff
 1  1.0      Angleterre    7  3  2  1  0   9   2    +7
 2  2.0      États-Unis    5  3  1  2  0   2   1    +1
 3  3.0            Iran    3  3  1  0  2   4   7    -3
 4  4.0  Pays de Galles    1  3  0  1  2   1   6    -5,
                                     0  \
 0                             Match 3
 1  21 novembre 2022 16 h heure locale
 2  21 novembre 2022 16 h heure locale

                                                    1        2  \
 0                                         Angleterre    6 - 2
 1  ( Shaw) Bellingham 35e ( Maguire) Saka 43e ( K...  (3 - 0)
 2                                                NaN  Rapport

                                                 3  \
 0                                            Iran
 1  65e Taremi (Gholizadeh )  90+13e (pén.) Taremi
 2                                             NaN

                                                    4  \
 0               Stade international de Khalifa, Doha
 1  Spectateurs : 45 334 Arbitrage : Raphael Claus...
 2  Spectateurs : 45 334 Arbitrage : Raphael Claus...

                                                    5
 0                                                NaN
 1  Spectateurs : 45 334 Arbitrage : Raphael Claus...
 2  Spectateurs : 45 334 Arbitrage : Raphael Claus...  ,
                                     0                    1        2  \
 0                             Match 4           États-Unis    1 - 1
 1  21 novembre 2022 22 h heure locale  ( Pulisic) Weah 36e  (1 - 0)
 2  21 novembre 2022 22 h heure locale                  NaN  Rapport

                  3                                                  4  \
 0   Pays de Galles                     Stade Ahmad-ben-Ali, Al Rayyan
 1  82e (pén.) Bale  Spectateurs : 43 418 Arbitrage : Abdulrahman A...
 2              NaN  Spectateurs : 43 418 Arbitrage : Abdulrahman A...

                                                    5
 0                                                NaN
 1  Spectateurs : 43 418 Arbitrage : Abdulrahman A...
 2  Spectateurs : 43 418 Arbitrage : Abdulrahman A...  ,
                                     0                    1        2  \
 0                            Match 17       Pays de Galles    0 - 2
 1  25 novembre 2022 13 h heure locale                  NaN  (0 - 0)
 2  25 novembre 2022 13 h heure locale  Wayne Hennessey 86e  Rapport

                                           3  \
 0                                      Iran
 1  90+8e Cheshmi  90+11e Rezaeian (Taremi )
 2                                       NaN

                                                    4  \
 0                     Stade Ahmad-ben-Ali, Al Rayyan
 1  Spectateurs : 40 875 Arbitrage : Mario Escobar...
 2  Spectateurs : 40 875 Arbitrage : Mario Escobar...

                                                    5
 0                                                NaN
 1  Spectateurs : 40 875 Arbitrage : Mario Escobar...
 2  Spectateurs : 40 875 Arbitrage : Mario Escobar...  ,
                                     0           1        2           3  \
 0                            Match 20  Angleterre    0 - 0  États-Unis
 1  25 novembre 2022 22 h heure locale         NaN  (0 - 0)         NaN
 2  25 novembre 2022 22 h heure locale         NaN  Rapport         NaN

                                                    4  \
 0                             Stade Al-Bayt, Al-Khor
 1  Spectateurs : 68 463 Arbitrage : Jesús Valenzu...
 2  Spectateurs : 68 463 Arbitrage : Jesús Valenzu...

                                                    5
 0                                                NaN
 1  Spectateurs : 68 463 Arbitrage : Jesús Valenzu...
 2  Spectateurs : 68 463 Arbitrage : Jesús Valenzu...  ,
                                     0               1        2  \
 0                            Match 33  Pays de Galles    0 - 3
 1  29 novembre 2022 22 h heure locale             NaN  (0 - 0)
 2  29 novembre 2022 22 h heure locale             NaN  Rapport

                                                    3  \
 0                                         Angleterre
 1  50e Rashford  51e Foden (Kane )  68e Rashford ...
 2                                                NaN

                                                    4  \
 0                     Stade Ahmad-ben-Ali, Al Rayyan
 1  Spectateurs : 44 297 Arbitrage : Slavko Vinčić...
 2  Spectateurs : 44 297 Arbitrage : Slavko Vinčić...

                                                    5
 0                                                NaN
 1  Spectateurs : 44 297 Arbitrage : Slavko Vinčić...
 2  Spectateurs : 44 297 Arbitrage : Slavko Vinčić...  ,
                                     0     1        2                    3  \
 0                            Match 34  Iran    0 - 1           États-Unis
 1  29 novembre 2022 22 h heure locale   NaN  (0 - 1)  38e Pulisic (Dest )
 2  29 novembre 2022 22 h heure locale   NaN  Rapport                  NaN

                                                    4  \
 0                             Stade Al-Thumama, Doha
 1  Spectateurs : 42 127 Arbitrage : Antonio Mateu...
 2  Spectateurs : 42 127 Arbitrage : Antonio Mateu...

                                                    5
 0                                                NaN
 1  Spectateurs : 42 127 Arbitrage : Antonio Mateu...
 2  Spectateurs : 42 127 Arbitrage : Antonio Mateu...  ,
      0                1    2  3  4  5  6   7   8     9
 0  NaN           Équipe  Pts  J  G  N  P  BP  BC  Diff
 1  1.0        Argentine    6  3  2  0  1   5   2    +3
 2  2.0          Pologne    4  3  1  1  1   2   2     0
 3  3.0          Mexique    4  3  1  1  1   2   3    -1
 4  4.0  Arabie saoudite    3  3  1  0  2   3   5    -2,
                                     0                 1        2  \
 0                             Match 8         Argentine    1 - 2
 1  22 novembre 2022 13 h heure locale  Messi 10e (pén.)  (1 - 0)
 2  22 novembre 2022 13 h heure locale               NaN  Rapport

                                               3  \
 0                               Arabie saoudite
 1  48e Al-Shehri (Al-Buraikan )  53e Al-Dawsari
 2                                           NaN

                                                    4  \
 0                            Stade de Lusail, Lusail
 1  Spectateurs : 88 012 Arbitrage : Slavko Vinčić...
 2  Spectateurs : 88 012 Arbitrage : Slavko Vinčić...

                                                    5
 0                                                NaN

In [164]:
goal_scorers = wc2022[87]
goal_scorers

   Place           Joueur  Buts  Passes décisives  Temps de jeu
0    NaN    Kylian Mbappé     8                 2           597
1    NaN     Lionel Messi     7                 3           690
2    NaN   Olivier Giroud     4                 0           383
3    4.0   Julián Álvarez     4                 0           467
4    5.0    Gonçalo Ramos     3                 1           153
5    6.0    Alvaro Morata     3                 1           183
6    7.0  Marcus Rashford     3                 0           137
7    8.0   Enner Valencia     3                 0           257
8    9.0      Bukayo Saka     3                 0           292
9   10.0      Richarlison     3                 0           326

In [165]:
goal_scorers.columns

Index(['Place', 'Joueur', 'Buts', 'Passes décisives', 'Temps de jeu'], dtype='object')

In [166]:
goal_scorers.drop(['Place'], axis = 1, inplace = True)
goal_scorers

            Joueur  Buts  Passes décisives  Temps de jeu
0    Kylian Mbappé     8                 2           597
1     Lionel Messi     7                 3           690
2   Olivier Giroud     4                 0           383
3   Julián Álvarez     4                 0           467
4    Gonçalo Ramos     3                 1           153
5    Alvaro Morata     3                 1           183
6  Marcus Rashford     3                 0           137
7   Enner Valencia     3                 0           257
8      Bukayo Saka     3                 0           292
9      Richarlison     3                 0           326

In [167]:
goal_scorers["But par minutes"] = goal_scorers["Temps de jeu"] / goal_scorers["Buts"]
goal_scorers

            Joueur  Buts  Passes décisives  Temps de jeu  But par minutes
0    Kylian Mbappé     8                 2           597        74.625000
1     Lionel Messi     7                 3           690        98.571429
2   Olivier Giroud     4                 0           383        95.750000
3   Julián Álvarez     4                 0           467       116.750000
4    Gonçalo Ramos     3                 1           153        51.000000
5    Alvaro Morata     3                 1           183        61.000000
6  Marcus Rashford     3                 0           137        45.666667
7   Enner Valencia     3                 0           257        85.666667
8      Bukayo Saka     3                 0           292        97.333333
9      Richarlison     3                 0           326       108.666667

In [168]:
goal_scorers.sort_values(by=["But par minutes"], ascending=False)

            Joueur  Buts  Passes décisives  Temps de jeu  But par minutes
3   Julián Álvarez     4                 0           467       116.750000
9      Richarlison     3                 0           326       108.666667
1     Lionel Messi     7                 3           690        98.571429
8      Bukayo Saka     3                 0           292        97.333333
2   Olivier Giroud     4                 0           383        95.750000
7   Enner Valencia     3                 0           257        85.666667
0    Kylian Mbappé     8                 2           597        74.625000
5    Alvaro Morata     3                 1           183        61.000000
4    Gonçalo Ramos     3                 1           153        51.000000
6  Marcus Rashford     3                 0           137        45.666667

In [169]:
goal_scorers

            Joueur  Buts  Passes décisives  Temps de jeu  But par minutes
0    Kylian Mbappé     8                 2           597        74.625000
1     Lionel Messi     7                 3           690        98.571429
2   Olivier Giroud     4                 0           383        95.750000
3   Julián Álvarez     4                 0           467       116.750000
4    Gonçalo Ramos     3                 1           153        51.000000
5    Alvaro Morata     3                 1           183        61.000000
6  Marcus Rashford     3                 0           137        45.666667
7   Enner Valencia     3                 0           257        85.666667
8      Bukayo Saka     3                 0           292        97.333333
9      Richarlison     3                 0           326       108.666667

In [170]:
url2 = "https://fr.wikipedia.org/wiki/Transfert_(football)"
transfert = pd.read_html(url2)
transfert

[                  Joueur              Provenance          Destination  \
 0                 Neymar            FC Barcelone  Paris Saint-Germain
 1          Kylian Mbappé               AS Monaco  Paris Saint-Germain
 2      Philippe Coutinho            Liverpool FC         FC Barcelone
 3         Moisés Caicedo  Brighton & Hove Albion           Chelsea FC
 4         Enzo Fernández        Benfica Lisbonne           Chelsea FC
 ..                   ...                     ...                  ...
 107  Alexandre Lacazette      Olympique lyonnais           Arsenal FC
 108          Timo Werner              RB Leipzig           Chelsea FC
 109     Gianluigi Buffon                Parme FC             Juventus
 110          André Onana             Inter Milan    Manchester United
 111        Gabriel Jesus         Manchester City           Arsenal FC

        Transfert (en euros)  Année
 0          222 millions[12]   2017
 1          180 millions[13]   2018
 2          135 millions[14]   2018
 3          133 millions[15]   2023
 4          121 millions[16]   2023
 ..                      ...    ...
 107         53 millions[71]   2017
 108             53 millions   2020
 109  52,8 millions[72],[73]   2001
 110           52,5 millions   2023
 111           52,3 millions   2022

 [112 rows x 5 columns],
                      Joueur              Provenance          Destination  \
 0                    Neymar            FC Barcelone  Paris Saint-Germain
 1                Paul Pogba                Juventus    Manchester United
 2               Gareth Bale       Tottenham Hotspur          Real Madrid
 3         Cristiano Ronaldo       Manchester United          Real Madrid
 4           Zinédine Zidane                Juventus          Real Madrid
 5                 Luís Figo            FC Barcelone          Real Madrid
 6             Hernán Crespo                Parme FC           Lazio Rome
 7           Christian Vieri              Lazio Rome          Inter Milan
 8                   Ronaldo            FC Barcelone          Inter Milan
 9              Alan Shearer        Blackburn Rovers         Newcastle FC
 10                  Ronaldo           PSV Eindhoven         FC Barcelone
 11        Gianluigi Lentini               Torino FC             AC Milan
 12          Gianluca Vialli            UC Sampdoria             Juventus
 13        Jean-Pierre Papin  Olympique de Marseille             AC Milan
 14           Roberto Baggio           AC Fiorentina             Juventus
 15              Ruud Gullit           PSV Eindhoven             AC Milan
 16           Diego Maradona            FC Barcelone           SSC Naples
 17           Diego Maradona            Boca Juniors         FC Barcelone
 18              Paolo Rossi                Juventus       Vicence Calcio
 19         Giuseppe Savoldi              Bologne FC           SSC Naples
 20             Johan Cruyff          Ajax Amsterdam         FC Barcelone
 21          Pietro Anastasi           Varèse Calcio             Juventus
 22           Harald Nielsen              Bologne FC          Inter Milan
 23           Angelo Sormani            Mantoue 1911              AS Rome
 24   Luis Suárez Miramontes            FC Barcelone          Inter Milan
 25              Omar Sívori             River Plate             Juventus
 26  Juan Alberto Schiaffino   Club Atlético Peñarol             AC Milan
 27            Hasse Jeppson        Atalanta Bergame           SSC Naples
 28            Jackie Sewell            Notts County  Sheffield Wednesday
 29              Trevor Ford             Aston Villa           Sunderland
 30            Eddie Quigley     Sheffield Wednesday    Preston North End
 31            Johnny Morris       Manchester United         Derby County
 32         Bernabé Ferreyra     Club Atlético Tigre          River Plate
 33               David Jack        Bolton Wanderers           Arsenal FC
 34                Bob Kelly              Burnley FC       Sunderland AFC
 35         Warney Cresswell           South Shields       Sunderland AFC
 36            Syd Puddefoot         West Ham United           Falkirk FC
 37               David Jack         Plymouth Argyle     Bolton Wanderers
 38             Percy Dawson     Heart of Midlothian     Blackburn Rovers
 39             Tommy Barber        Bolton Wanderers          Aston Villa
 40              Daniel Shea         West Ham United     Blackburn Rovers
 41               Alf Common          Sunderland AFC     Middlesbrough FC
 42            Andy McCombie          Sunderland AFC     Newcastle United
 43                Ben Green             Barnsley FC          Small Heath
 44            Willie Groves           West Bromwich          Aston Villa

            Transfert (en euros)  Année
 0              222 millions[12]   2017
 1              105 millions[21]   2016
 2             99,7 millions[24]   2013
 3               94 millions[26]   2009
 4               75 millions[41]   2001
 5                 61,7 millions   2000
 6                 56,5 millions   2000
 7             42,6 millions[74]   1999
 8                 30,5 millions   1997
 9   17 millions[réf. souhaitée]   1996
 10                14,9 millions   1996
 11                14,7 millions   1992
 12                13,6 millions   1992
 13                11,3 millions   1992
 14                   9 millions   1990
 15                 6,8 millions   1987
 16                 5,6 millions   1984
 17                 3,4 millions   1982
 18                  1,9 million   1976
 19                  1,3 million   1975
 20                    1 million   1973
 21                      568 000   1968
 22                      340 000   1967
 23                      284 000   1963
 24                      172 000   1961
 25                      105 000   1957
 26                       81 800   1954
 27                       59 000   1952
 28                       39 000   1951
 29                       34 000   1950
 30                       30 000   1949
 31                       27 000   1949
 32                       26 000   1932
 33                       12 300   1928
 34                        7 400   1925
 35                        6 200   1922
 36                        5 700   1922
 37                        4 000   1920
 38                        2 800   1914
 39                        2 300   1913
 40                        2 300   1913
 41                        1 140   1905
 42                          800   1904
 43                          570   1903
 44                          113   1893  ,
                Nom                Provenance          Destination  \
 0           Neymar              FC Barcelone  Paris Saint-Germain
 1    Kylian Mbappé                 AS Monaco  Paris Saint-Germain
 2   Edinson Cavani                SSC Naples  Paris Saint-Germain
 3   Ángel Di María         Manchester United  Paris Saint-Germain
 4    Achraf Hakimi               Inter Milan  Paris Saint-Germain
 5    Manuel Ugarte               Sporting CP  Paris Saint-Germain
 6     Mauro Icardi               Inter Milan  Paris Saint-Germain
 7       David Luiz                Chelsea FC  Paris Saint-Germain
 8  Leandro Paredes  Zénith Saint-Pétersbourg  Paris Saint-Germain
 9  James Rodríguez                  FC Porto            AS Monaco

   Montant (en euros)  Année
 0   222 millions[12]   2017
 1   180 millions[13]   2018
 2    64 millions[52]   2013
 3    63 millions[54]   2015
 4    60 millions[61]   2021
 5        60 millions   2023
 6    50 millions[76]   2020
 7  49,5 millions[77]   2014
 8    47 millions[78]   2019
 9    45 millions[79]   2013  ,
                    Nom                   Provenance          Destination  \
 0        Kylian Mbappé                    AS Monaco  Paris Saint-Germain
 1       Victor Osimhen                   LOSC Lille           SSC Naples
 2         Nicolas Pépé                   LOSC Lille           Arsenal FC
 3  Aurélien Tchouaméni                    AS Monaco          Real Madrid
 4      James Rodríguez                    AS Monaco          Real Madrid
 5         Thomas Lemar                    AS Monaco      Atlético Madrid
 6      Anthony Martial                    AS Monaco    Manchester United
 7      Tanguy Ndombele           Olympique lyonnais    Tottenham Hotspur
 8          Jérémy Doku  Stade rennais Football Club      Manchester City
 9       Benjamin Mendy                    AS Monaco      Manchester City

              Montant (en euros)  Année
 0              180 millions[13]   2018
 1             81,3 millions[35]   2020
 2               80 millions[38]   2019
 3                   80 millions   2022
 4               78 millions[40]   2014
 5               65 millions[51]   2018
 6               60 millions[59]   2015
 7  60 millions[réf. nécessaire]   2019
 8               60 millions[63]   2023
 9             57,5 millions[66]   2017  ,
                    Nom         Provenance             Destination  \
 0       Jonathan David    KAA La Gantoise               Lille OSC
 1          Jéremy Doku     RSC Anderlecht           Stade rennais
 2               Wesley     Club Bruges KV             Aston Villa
 3      Youri Tielemans     RSC Anderlecht               AS Monaco
 4     Odilon Kossounou     Club Bruges KV        Bayer Leverkusen
 5         Sander Berge           KRC Genk        Sheffield United
 6       Victor Osimhen      Charleroi RSC               Lille OSC
 7    Marouane Fellaini  Standard de Liège              Everton FC
 8     Leandro Trossard           KRC Genk  Brighton & Hove Albion
 9  Aleksandar Mitrović     RSC Anderlecht        Newcastle United

   Montant (en euros)  Année
 0        32 millions   2020
 1        26 millions   2020
 2        25 millions   2019
 3        25 millions   2017
 4        23 millions   2021
 5        23 millions   2020
 6      22,4 millions   2019
 7      21,7 millions   2008
 8        20 millions   2019
 9      18,5 millions   2015  ,
                    Nom               Provenance               Destination  \
 0         Breel Embolo                  FC Bâle                Schalke 04
 1        Manuel Akanji                  FC Bâle         Borussia Dortmund
 2  Mohamed Elyounoussi                  FC Bâle            Southampton FC
 3        Mohamed Salah                  FC Bâle                Chelsea FC
 4        Matheus Cunha                  FC Sion                RB Leipzig
 5       Mohamed Elneny                  FC Bâle                Arsenal FC
 6        Denis Zakaria           BSC Young Boys  Borussia Mönchengladbach
 7      Xherdan Shaqiri                  FC Bâle             Bayern Munich
 8           Bernt Haas  Grasshopper Club Zurich            Sunderland AFC
 9         Albian Ajeti                  FC Bâle        West Ham United FC

   Montant (en euros)  Année
 0      26,5 millions   2016
 1      21,5 millions   2018
 2        18 millions   2018
 3      16,5 millions   2014
 4        15 millions   2018
 5      12,5 millions   2014
 6        12 millions   2017
 7      11,8 millions   2012
 8      11,8 millions   2001
 9      11,3 millions   2020  ,
    Rang                 Joueuse          Provenance         Destination  \
 0     1      Racheal Kundananji          Madrid CFF              Bay FC
 1     2            Barbra Banda    Shanghai Shengli       Orlando Pride
 2     3           Mayra Ramírez          Levante UD          Chelsea FC
 3     4             Keira Walsh     Manchester City        FC Barcelone
 4     5           Lena Oberdorf       VfL Wolfsburg       Bayern Munich
 5     6              Jill Roord       VfL Wolfsburg     Manchester City
 6     7       Kyra Cooney-Cross         Hammarby IF          Arsenal FC
 7     8           Lindsey Horan  Thorns de Portland  Olympique lyonnais
 8     8                   Geyse        FC Barcelone   Manchester United
 9    10  Scarlett Camberos (en)        Club América       Angel City FC

       Montant  Année         Réf.
 0   805 000 €   2024         [84]
 1   681 000 €   2024         [91]
 2   500 000 €   2024         [92]
 3   470 000 €   2022    [93],[94]
 4   450 000 €   2024         [95]
 5  >350 000 €   2023         [96]
 6   350 000 €   2023         [97]
 7   300 000 €   2023         [98]
 8   300 000 €   2023         [99]
 9  >285 000 €   2023  [100],[101]  ,
    Rang           Joueuse             Provenance          Destination  \
 0     1     Lindsey Horan     Thorns de Portland   Olympique lyonnais
 1     2       Mary Fowler        Montpellier HSC      Manchester City
 2     3           Tainara  Girondins de Bordeaux        Bayern Munich
 3     4  Kadidiatou Diani               Paris FC  Paris Saint-Germain
 4     4    Jackie Groenen      Manchester United  Paris Saint-Germain
 5     6   Ellie Carpenter     Thorns de Portland   Olympique lyonnais
 6     7    Valérie Gauvin        Montpellier HSC           Everton FC
 7     8     Griedge Mbock            EA Guingamp   Olympique lyonnais
 8     8  Damaris Egurrola             Everton FC   Olympique lyonnais
 9     8     Nikita Parris     Olympique lyonnais              Arsenal

       Montant  Année         Réf.
 0   300 000 €   2023         [98]
 1   190 000 €   2022  [104],[105]
 2  >150 000 €   2022        [104]
 3   150 000 €   2017        [103]
 4   150 000 €   2022        [106]
 5  >110 000 €   2020        [107]
 6  >100 000 €   2020        [108]
 7   100 000 €   2015        [103]
 8   100 000 €   2021        [109]
 9   100 000 €   2021        [110]  ,
   v · mListes des plus grandes dépenses  \
 0                                 Média
 1                                 Lieux
 2                                 Sport
 3                             Véhicules

              v · mListes des plus grandes dépenses.1
 0  Films Jeux vidéo Peintures Photographies Sculp...
 1                                        Villes Rues
 2                      Transfert (football) Contrats
 3                                              Motos  ]

In [171]:
df = transfert[0]
df

,Joueur,Provenance,Destination,Transfert (en euros),Année
0,Neymar,FC Barcelone,Paris Saint-Germain,222 millions[12],2017
1,Kylian Mbappé,AS Monaco,Paris Saint-Germain,180 millions[13],2018
2,Philippe Coutinho,Liverpool FC,FC Barcelone,135 millions[14],2018
3,Moisés Caicedo,Brighton & Hove Albion,Chelsea FC,133 millions[15],2023
4,Enzo Fernández,Benfica Lisbonne,Chelsea FC,121 millions[16],2023
...,...,...,...,...,...
107,Alexandre Lacazette,Olympique lyonnais,Arsenal FC,53 millions[71],2017
108,Timo Werner,RB Leipzig,Chelsea FC,53 millions,2020
109,Gianluigi Buffon,Parme FC,Juventus,"52,8 millions[72],[73]",2001
110,André Onana,Inter Milan,Manchester United,"52,5 millions",2023
111,Gabriel Jesus,Manchester City,Arsenal FC,"52,3 millions",2022

In [172]:
df[["Prix","Millions"]] = df['Transfert (en euros)'].str.split(' ',expand=True)
df

,Joueur,Provenance,Destination,Transfert (en euros),Année,Prix,Millions
0,Neymar,FC Barcelone,Paris Saint-Germain,222 millions[12],2017,222,millions[12]
1,Kylian Mbappé,AS Monaco,Paris Saint-Germain,180 millions[13],2018,180,millions[13]
2,Philippe Coutinho,Liverpool FC,FC Barcelone,135 millions[14],2018,135,millions[14]
3,Moisés Caicedo,Brighton & Hove Albion,Chelsea FC,133 millions[15],2023,133,millions[15]
4,Enzo Fernández,Benfica Lisbonne,Chelsea FC,121 millions[16],2023,121,millions[16]
...,...,...,...,...,...,...,...
107,Alexandre Lacazette,Olympique lyonnais,Arsenal FC,53 millions[71],2017,53,millions[71]
108,Timo Werner,RB Leipzig,Chelsea FC,53 millions,2020,53,millions
109,Gianluigi Buffon,Parme FC,Juventus,"52,8 millions[72],[73]",2001,"52,8","millions[72],[73]"
110,André Onana,Inter Milan,Manchester United,"52,5 millions",2023,"52,5",millions
111,Gabriel Jesus,Manchester City,Arsenal FC,"52,3 millions",2022,"52,3",millions

In [173]:
df['Prix'] = df["Prix"].str.replace(",", ".")
df

,Joueur,Provenance,Destination,Transfert (en euros),Année,Prix,Millions
0,Neymar,FC Barcelone,Paris Saint-Germain,222 millions[12],2017,222,millions[12]
1,Kylian Mbappé,AS Monaco,Paris Saint-Germain,180 millions[13],2018,180,millions[13]
2,Philippe Coutinho,Liverpool FC,FC Barcelone,135 millions[14],2018,135,millions[14]
3,Moisés Caicedo,Brighton & Hove Albion,Chelsea FC,133 millions[15],2023,133,millions[15]
4,Enzo Fernández,Benfica Lisbonne,Chelsea FC,121 millions[16],2023,121,millions[16]
...,...,...,...,...,...,...,...
107,Alexandre Lacazette,Olympique lyonnais,Arsenal FC,53 millions[71],2017,53,millions[71]
108,Timo Werner,RB Leipzig,Chelsea FC,53 millions,2020,53,millions
109,Gianluigi Buffon,Parme FC,Juventus,"52,8 millions[72],[73]",2001,52.8,"millions[72],[73]"
110,André Onana,Inter Milan,Manchester United,"52,5 millions",2023,52.5,millions
111,Gabriel Jesus,Manchester City,Arsenal FC,"52,3 millions",2022,52.3,millions

In [174]:
df.drop(["Millions"], axis = 1, inplace = True)
df

,Joueur,Provenance,Destination,Transfert (en euros),Année,Prix
0,Neymar,FC Barcelone,Paris Saint-Germain,222 millions[12],2017,222
1,Kylian Mbappé,AS Monaco,Paris Saint-Germain,180 millions[13],2018,180
2,Philippe Coutinho,Liverpool FC,FC Barcelone,135 millions[14],2018,135
3,Moisés Caicedo,Brighton & Hove Albion,Chelsea FC,133 millions[15],2023,133
4,Enzo Fernández,Benfica Lisbonne,Chelsea FC,121 millions[16],2023,121
...,...,...,...,...,...,...
107,Alexandre Lacazette,Olympique lyonnais,Arsenal FC,53 millions[71],2017,53
108,Timo Werner,RB Leipzig,Chelsea FC,53 millions,2020,53
109,Gianluigi Buffon,Parme FC,Juventus,"52,8 millions[72],[73]",2001,52.8
110,André Onana,Inter Milan,Manchester United,"52,5 millions",2023,52.5
111,Gabriel Jesus,Manchester City,Arsenal FC,"52,3 millions",2022,52.3

In [175]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112 entries, 0 to 111
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Joueur                112 non-null    object
 1   Provenance            112 non-null    object
 2   Destination           112 non-null    object
 3   Transfert (en euros)  112 non-null    object
 4   Année                 112 non-null    int64
 5   Prix                  112 non-null    object
dtypes: int64(1), object(5)
memory usage: 5.4+ KB

In [176]:
df["Prix"] = df["Prix"].astype(float)
df.head()

,Joueur,Provenance,Destination,Transfert (en euros),Année,Prix
0,Neymar,FC Barcelone,Paris Saint-Germain,222 millions[12],2017,222.0
1,Kylian Mbappé,AS Monaco,Paris Saint-Germain,180 millions[13],2018,180.0
2,Philippe Coutinho,Liverpool FC,FC Barcelone,135 millions[14],2018,135.0
3,Moisés Caicedo,Brighton & Hove Albion,Chelsea FC,133 millions[15],2023,133.0
4,Enzo Fernández,Benfica Lisbonne,Chelsea FC,121 millions[16],2023,121.0

In [177]:
df.drop(['Transfert (en euros)'],axis=1,inplace=True)
df

,Joueur,Provenance,Destination,Année,Prix
0,Neymar,FC Barcelone,Paris Saint-Germain,2017,222.0
1,Kylian Mbappé,AS Monaco,Paris Saint-Germain,2018,180.0
2,Philippe Coutinho,Liverpool FC,FC Barcelone,2018,135.0
3,Moisés Caicedo,Brighton & Hove Albion,Chelsea FC,2023,133.0
4,Enzo Fernández,Benfica Lisbonne,Chelsea FC,2023,121.0
...,...,...,...,...,...
107,Alexandre Lacazette,Olympique lyonnais,Arsenal FC,2017,53.0
108,Timo Werner,RB Leipzig,Chelsea FC,2020,53.0
109,Gianluigi Buffon,Parme FC,Juventus,2001,52.8
110,André Onana,Inter Milan,Manchester United,2023,52.5
111,Gabriel Jesus,Manchester City,Arsenal FC,2022,52.3

In [178]:
df = df.rename(columns={"Prix" : "Prix en millions d'Euro"})
df

,Joueur,Provenance,Destination,Année,Prix en millions d'Euro
0,Neymar,FC Barcelone,Paris Saint-Germain,2017,222.0
1,Kylian Mbappé,AS Monaco,Paris Saint-Germain,2018,180.0
2,Philippe Coutinho,Liverpool FC,FC Barcelone,2018,135.0
3,Moisés Caicedo,Brighton & Hove Albion,Chelsea FC,2023,133.0
4,Enzo Fernández,Benfica Lisbonne,Chelsea FC,2023,121.0
...,...,...,...,...,...
107,Alexandre Lacazette,Olympique lyonnais,Arsenal FC,2017,53.0
108,Timo Werner,RB Leipzig,Chelsea FC,2020,53.0
109,Gianluigi Buffon,Parme FC,Juventus,2001,52.8
110,André Onana,Inter Milan,Manchester United,2023,52.5
111,Gabriel Jesus,Manchester City,Arsenal FC,2022,52.3

In [183]:
group_by = df[['Destination', "Prix en millions d'Euro"]].groupby("Destination").sum()
group_by

                     Prix en millions d'Euro
Destination
Al-Hilal FC                            195.0
Arsenal FC                             434.3
Aston Villa                             55.0
Atlético de Madrid                     296.0
Bayern Munich                          247.0
Chelsea FC                            1275.3
FC Barcelone                           842.7
Inter Milan                             83.0
Juventus                               467.3
Lazio Rome                              56.5
Liverpool FC                           351.5
Manchester City                       1095.9
Manchester United                     1079.7
Newcastle United                       135.0
Paris Saint-Germain                    739.0
Real Madrid                            816.4
SSC Naples                              81.3
Shangaï SIPG                           125.8
Tottenham Hotspur                      118.0

In [185]:
group_by.sort_values(by=["Prix en millions d'Euro"], ascending = False)

                     Prix en millions d'Euro
Destination
Chelsea FC                            1275.3
Manchester City                       1095.9
Manchester United                     1079.7
FC Barcelone                           842.7
Real Madrid                            816.4
Paris Saint-Germain                    739.0
Juventus                               467.3
Arsenal FC                             434.3
Liverpool FC                           351.5
Atlético de Madrid                     296.0
Bayern Munich                          247.0
Al-Hilal FC                            195.0
Newcastle United                       135.0
Shangaï SIPG                           125.8
Tottenham Hotspur                      118.0
Inter Milan                             83.0
SSC Naples                              81.3
Lazio Rome                              56.5
Aston Villa                             55.0